services:
  php:
    container_name: test-php
    build:
      context: ./
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - './www:/var/www/html'
    ports:
      - "${DOCKER_PROJECT_IP}:${DOCKER_FPM_PORT}:9000"
    networks:
      - php-test
    restart: always

  nginx:
    container_name: test-nginx
    image: nginx:latest
    ports:
      - '${DOCKER_NGINX_PORT}:80'
    volumes:
      - './www:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - php-test
    restart: always
    depends_on:
      - php

  mysql:
    container_name: test-mysql
    image: mysql:latest
    volumes:
      - test-db-vol:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: [
      "--log_bin_trust_function_creators=1",
      "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    ports:
      - "${DOCKER_PROJECT_IP}:${DOCKER_DB_PORT}:3306"
    networks:
      - php-test
    restart: always

networks:
  php-test:
    driver: bridge

volumes:
  test-db-vol: